### PR TITLE
Wireframes for Home page Added

### PR DESCRIPTION
**Pull request by shreyateeza**
Solves a part of issue #2 

## What all changes are included in this PR?
1. A separate folder named 'Wireframes' has been added. In it, three different mockups of the home page are there.
2. Of course, there will be infinite scroll kind of structure(as observed in the three given links in issue #2) but on scrolling, they will link to other tabs as far as I observed. That's why I have created only the main(home) part.
3. If you want any changes in mock-ups, do comment below I will update them either in this PR or a new one as mentors/admin say.

## Is there anything left to be done in the addressed issue? If yes, then state the remaining tasks here.
This PR solves a part of issue #2

### CODE REVIEW

**Comment by shreyateeza** [comment]
@lalitmee Please review this PR.

**Comment by lalitmee** [comment]
Hey @shreyateeza, 
- First of all, I would like to appreciate your effort and thank you for following the pull request template. :+1: 
- You did a great job in creating these wireframes. :100: 

## **About the Design** 
  - Designs are looking good.
  - The only thing which is looking a little bit off is the color schemes which you have choosen.
  - I think you should modify the colors of the designs.

But you can wait for the review of other mentors, what they say about the color scheme. :innocent:

**Comment by shreyateeza** [comment]
@lalitmee Thank you so much for the appreciation! :)
Actually, @jayeshkattar told to submit it by today morning so I was in a hurry. I apologise for this.

**Comment by troublemagnet** [comment]
Hi @shreyateeza, great work!! 

Few things you can improve on - 
1) In 1.1, if you could change the font color of Kranti, it'll be great. I agree, red-white is a great combo but because of the background, it looks a bit hidden I guess.
2)  In 2.3, I suggest you choose a different font face and color. The color font face looks very informal and doesn't go well with the front page font I guess.
3) I like the impact of kranti in 3.1.
4) I have same suggestions for 3.2 as 2.3. Also 3.2 is very textual IMO.

**Review by amritsrivastava — COMMENTED** [review]
The design is good @shreyateeza but I think the header is not looking good at the bottom, one more issue that I realized is the that the color combination is not catchy, there are too many bright colors that irritate eyes, I think we should take two background schemes and use them alternatively (like blue and white backgrounds or grey and white).

**Comment by shreyateeza** [comment]
@amritsrivastava  I am working on updating the colour combination.
As far as the header is concerned, I think that can be done while coding the website and this is just a wireframe. :sweat_smile:

**Comment by shreyateeza** [comment]
I used WP online to design the wireframes. In it, I am having trouble changing the menu items' colour.
I googled for the solution and found that it can be done by using the desktop app. Now there is some issue in installing the app which I am trying to resolve.
I will give the final update after 24 hours.
@troublemagnet @lalitmee please note.

**Comment by troublemagnet** [comment]
@shreyateeza any updates?

**Comment by shreyateeza** [comment]
Wordpress is not getting installed on the desktop.
Can I submit without changing the font colour/style of menu items @troublemagnet?

**Review by 0x48piraj — APPROVED** [review]

**Comment by 0x48piraj** [comment]
I think you can, but, be sure to open a related issue for adjusting the font face/colors.
It'll create opportunity window for another participant, IMO.

**Comment by troublemagnet** [comment]
@shreyateeza is the problem still not resolved without your wordpress?

**Comment by shreyateeza** [comment]
@troublemagnet Unfortunately no, it's still not resolved :(
I have installed the Wordpress app but the problem is when I open it, it always asks me to download the latest version(I did download but still the same older version appears and with the same notification popping up timely). Even if I continue to use the older version, it shows the same way as the website on a browser means having no additional things to edit in detail. :disappointed_relieved: 
I use Ubuntu 18.04. Maybe on other OS, this problem should not occur.

**Comment by shreyateeza** [comment]
@AvaniVerma @troublemagnet 
We can consider the colors used in the current website of Kranti using the wireframes I have created.
Would like to know suggestions on this.

**Comment by AvaniVerma** [comment]
@shreyateeza I like the idea but please implement it as well. Provide the code for the same. This will be counted for #2 and the code for #17.

**Pull request closed without merging**
