### PR TITLE
kranti logo added

### PR DESCRIPTION
**Pull request by saberprashant**
closes #

fixes #

## What all changes are included in this PR?
I am submitting a PR for the "Design SVG Logo" issue under GSSOC. I've added a .png file for the logo but I also have its SVG.
## Is there anything left to be done in the addressed issue? If yes, then state the remaining tasks here.
No, but I am open for suggestions :)    
  
## Why I made this logo (Significance)?
So, while making this logo, I understand that Kranti wants to bring a change in the life of women by providing education facility, healing home and mainly a way so that, they can change their life and get the freedom to do anything. That's why I used a "Book" to show the significance of Education and a "Torch in Woman Hands" to show a hope to bring the change and world of opportunities.  :)

### CODE REVIEW

**Review by shreyateeza — COMMENTED** [review]
Simple and elegant! :slightly_smiling_face:

**Comment by troublemagnet** [comment]
Hi, I like the idea. It'll be better though if you could add some colors. So, to this PR just add one more image of the colored one so we can compare and see.

**Comment by Pratul1997** [comment]
@troublemagnet I agree with your saying,
If possible @saberprashant try to add colors to it and also add the SVG format along with it.
@saberprashant  Your work is quite good, appreciated. :+1:

**Comment by AvaniVerma** [comment]
@saberprashant The design is beautiful. I like the font you have used. Further, as suggested by @troublemagnet and @Pratul1997 , please add a colorful SVG format. You can either fill color in the current design or make different parts of the logo with different colored lines.

**Comment by saberprashant** [comment]
Hi @shreyateeza @troublemagnet @Pratul1997 @AvaniVerma , I am glad that you liked my idea. And yes, I will try to add some colours to this logo as per your suggestions and will add an SVG too in the existing PR.
Thanks :)

**Review by 0x48piraj — APPROVED** [review]
Great first contribution!
Keep it up :)

**Comment by troublemagnet** [comment]
@saberprashant any updates?

**Comment by saberprashant** [comment]
Yeah I am working on it, will surely add a colour logo by end of tomorrow.
:)

**Comment by saberprashant** [comment]
Hi @troublemagnet @AvaniVerma @Pratul1997, I have added a coloured logo with its SVG and also added the SVG for the B&W logo.
Well, in my opinion, it would be good if we go with the B&W logo, as we can use it anywhere without thinking of changing the background for it, when we use it on different screens and places, plus if we are designing anything specific like a poster or something then a simple stroked logo can take the full style of that poster as well. So, that's why a B&W logo would be good. Still, the decision will be yours and other mentors. I would be happy if you like anyone :)  
Thank you.

**Comment by AvaniVerma** [comment]
@saberprashant  Very nicely done. I also like the B&W one.

**Review by troublemagnet — APPROVED** [review]
Amazing, LGTM! @lalitmee @Pratul1997 please review.

**Review by lalitmee — APPROVED** [review]
Awesome... 
The logo is looking great. :+1:

**Comment by troublemagnet** [comment]
Merging this PR for now. We'll see whether to use the uncolored one or the colored one later!

**Pull request merged**
