### PR TITLE
Meet The Revolutionary Tab Created

### LINKED ISSUE #3: Create Tabs
Homepage 
Meet the Revolutionaries 
Support
FAQs
Press
Contact
Blog

Content Here: https://drive.google.com/drive/folders/0BwpCIeAR0xFcTVlXc1FvQXZvcHM?usp=sharing

### PR DESCRIPTION
**Pull request by vaarigupta**
closes #3 
## What all changes are included in this PR?
##Meet the Revolutionary tab lay out Created :+1: 

#####**Changes**
screenshot-2018-7-7 react app
screenshot-2018-7-7 react app 2

**app.js** -> Added < Meet /> class 
**src/Meet_the_revol(folder) ->** 
- Meet_the_revol.js -> Created the entire code for the revolutionary description
- Meet_the_revol.css -> Enhanced the Formatting of Code and Improved its styling but I have to modify more and make it look fascinating .
**ADDED DEPENDENCY ->**

1. @material-ui/core": "^1.3.1"
2. "materialize-css": "0.100.2"
3.react-material-icons": "^1.0.3"
Do Look at my work.

### CODE REVIEW

**Comment by lalitmee** [comment]
Hey @vaarigupta, can you show some screenshot of the page which you have developed. Actually, I was trying to run your PR but it was showing some error in materialize. :+1:

**Comment by tulikatewari** [comment]
@vaarigupta Yes I agree with @lalitmee .

**Comment by vaarigupta** [comment]
@lalitmee  I added this layout . I have created a layout and I am gonna modify this in few days as I was stuck with issue of adding materialize icons in this 
Ex- you can see that It's showing tap and close but there should be icons instead of that .
The width and height of each card needs to be adjusted more so that it will become eye catchy

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
Resolve the branch conflicts :)

**Comment by AvaniVerma** [comment]
@vaarigupta Hey, have you made the changes ?

**Comment by vaarigupta** [comment]
@0x48piraj  OKK I will do it by tomorrow

**Comment by vaarigupta** [comment]
@AvaniVerma , I have to make changes . I will let you know by tomorrow

**Comment by troublemagnet** [comment]
@vaarigupta if you're facing any problems in resolving the conflicts, let us know.

**Comment by vaarigupta** [comment]
@troublemagnet yess , I'm facing as I am learning react as I m at the beginner level so I have some issues with jsx as whatever the output I was expecting ..I didn't get

**Comment by troublemagnet** [comment]
@vaarigupta can you please explain in detail where you're stuck?

**Comment by troublemagnet** [comment]
@vaarigupta any updates? Otherwise we'll have to close the PR due to inactivity.

**Pull request closed without merging**
