### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by adi44**
Done!!!!

### CODE REVIEW

**Comment by lalitmee** [comment]
Oh Great. But I am not getting that why you named this PR this **Add files via upload**. And for the file also you name it `Simple Program.js`, I would request you to change it to `App.js`. 

Why you didn't follow any boilerplate like `create-react-app`? :thinking:

**Comment by adi44** [comment]
there was some problem in my laptop so thats why for create-react-app

**Comment by lalitmee** [comment]
At least change the file name as I suggested.

**Comment by adi44** [comment]
ok

**Comment by adi44** [comment]
I have changed it pls do check

**Pull request closed without merging**
