### PR TITLE
New Logo

### PR DESCRIPTION
**Pull request by adi44**
closes #

fixes #

### CODE REVIEW

**Comment by vaarigupta** [comment]
@adi44  how to see your code instead of going your profile ? could you please guide me ?

**Comment by amritsrivastava** [comment]
@adi44 your logo looks pretty good and relevant. Btw why you added another file Simple Program.js

**Comment by shreyateeza** [comment]
@adi44  The tagline says 'Empower Women' but on the other hand, the head of the woman is tilted downwards. I think the logo must contain the face of the woman looking upwards.

**Comment by lalitmee** [comment]
Hey @adi44, are you updating the logo with the changes in the head of the woman. :thinking:

**Comment by shreyateeza** [comment]
@adi44 This issue can be closed as you have created PR #12 with the requested changes.

**Pull request closed without merging**
