### PR TITLE
Sample logos have been added

### PR DESCRIPTION
**Pull request by shreyateeza**
Solves #8 

## What all changes are included in this PR?
Logo samples have been added. Both png and SVG files are available.

## Is there anything left to be done in the addressed issue? If yes, then state the remaining tasks here.
Nothing is left to be done in the addressed issue.

### CODE REVIEW

**Comment by lalitmee** [comment]
Hey @shreyateeza, actually I didn't get the message which you want to convey from these logo's designs. :wink: Can you explain to me that why you chose this outlook? :innocent:

**Comment by shreyateeza** [comment]
Significance of colors used in [five.png](https://github.com/shreyateeza/Kranti/blob/fd36a18ccbba5ed0d24dec366aeeb530272cabec/Logo-samples/five.png) from bottom to top:
1. **Embers**: a small piece of burning or glowing coal or wood in a dying fire(See [here](https://www.google.co.in/search?q=ember+meaning&oq=ember&aqs=chrome.1.69i57j69i59j69i60l2j0l2.3836j1j4&sourceid=chrome&ie=UTF-8)) - relates to this line, "empowers girls from Mumbai's red-light areas"
2. **Posy**:  small bunch of flowers(See [here](https://www.google.co.in/search?ei=uUE6W76QHIP4vgTzpIuwBQ&q=posy+meaning&oq=posy+meaning&gs_l=psy-ab.3..0i67k1j0i7i30k1j0j0i7i30k1l3j0j0i7i30k1j0i7i10i30k1l2.52561.53321.0.54318.4.4.0.0.0.0.148.418.0j3.3.0....0...1.1.64.psy-ab..1.3.414....0.CAwc3piTS4c)) - relates to line, "empowers girls to become agents of social change"(flowers and agents of social change both resemble goodness/virtue)
3. **Ink**: See [here](http://www.bhgraphology.co.uk/colours-of-ink-their-meaning) the meaning of Blue Ink. "...understanding, caring, reflective and emotional..." - This is what Krantikaris(Revolutionaries) are. Right?
4. **Gold**: The color Gold is associated with illumination, love, compassion, courage, passion, magic, and wisdom. See [here](https://www.bourncreative.com/meaning-of-the-color-gold/).

As mentioned in issue #2 , the desired colors were-
1. Red: Ember is similar to dark red.  Ember colored ellipse is kept at base representing the strong foundation.
2. Purple: Posy is similar to Purple.
3. Blue: Ink is similar to dark blue.

**Comment by shreyateeza** [comment]
@lalitmee @troublemagnet That is why I chose these colors.
I made a pyramid kind of logo because of [this](https://www.google.co.in/search?ei=u0M6W97tPIS0vwSn-rzYDA&q=significance+of+pyramid+shape&oq=significance+of+pyr&gs_l=psy-ab.3.3.0l9.43919.50888.0.60461.35.15.3.0.0.0.516.2071.0j5j1j1j1j1.9.0....0...1.1.64.psy-ab..25.10.1235...0i67k1j0i22i30k1.0.r1OdOxNhUpw) and [this](http://vaastuvedas.com/pyramids_and_vaastu.html) reasons.

I used ellipses at each level because this looks good.

**Comment by shreyateeza** [comment]
@AvaniVerma Here is the reason for the kind of logo I have created.

**Comment by AvaniVerma** [comment]
@shreyateeza I like how the logo is meaningful. But the same things convey different meanings in different parts of the world. 
Also, the logo looks similar to that of Tower Research Capital, a colored and compressed version. This can be a problem(logo copying).

**Comment by shreyateeza** [comment]
@AvaniVerma I don't think that there will be such an issue. There is a lot of difference between the two.

**Comment by amritsrivastava** [comment]
Good work @AvaniVerma, but I want to say that logo must be catchy that looks good kindly use some designing skills and make it a little bit attractive.

**Comment by AvaniVerma** [comment]
Cool. Your choice.

**Comment by troublemagnet** [comment]
Hi, I love the meaning behind logo but can you work a little on it's appearance?

**Comment by shreyateeza** [comment]
@troublemagnet sure!
But can you provide me some ideas please?

**Comment by AvaniVerma** [comment]
@shreyateeza Relax, you have more than a month to come up with an idea and design it. I really want you to try it yourself.

**Review by 0x48piraj — APPROVED** [review]

**Comment by troublemagnet** [comment]
@shreyateeza any updates?

**Comment by shreyateeza** [comment]
@troublemagnet I am still exploring better options. Would like to take some more time.

**Comment by troublemagnet** [comment]
@shreyateeza do you need any help?

**Comment by shreyateeza** [comment]
@troublemagnet I couldn't find a better alternative. I leave it up to you and other mentors if they want to accept this logo or not.

**Comment by troublemagnet** [comment]
While we really appreciate the efforts and idea you put in to make this logo, I'm afraid we can't accept it. The reason being one of the most important requirements of kranti was visual appearance.

**Comment by shreyateeza** [comment]
No problem @troublemagnet. Closing this PR.

**Pull request closed without merging**
