### PR TITLE
Kranti Logo

### PR DESCRIPTION
**Pull request by adi44**
closes #

fixes #

### CODE REVIEW

**Comment by Pratul1997** [comment]
@jayeshkattar 
This looks good to me, :+1: 
Waiting for reviews from other mentors too

**Comment by shreyateeza** [comment]
Is the SVG file of this logo ready? As the issue #8 asks for an SVG logo.
Also please update the PR template.

**Comment by adi44** [comment]
I will provide svg file

**Comment by troublemagnet** [comment]
@adi44 I really like the logo, but I think we'll wait for some time before deciding if this is the final one since the colour scheme hasn't been decided. Once the color scheme is decided, you might have to make some changes in the colors of the logo. Otherwise LGTM!

**Review by 0x48piraj — APPROVED** [review]
LGTM!

> For the next time, be sure to point out the issue you're solving in the description.

**Review by lalitmee — COMMENTED** [review]
LGTM

**Review by troublemagnet — APPROVED** [review]
@AvaniVerma @lalitmee @Pratul1997 should we merge this? LGTM.

**Comment by Pratul1997** [comment]
@troublemagnet @lalitmee And I am good with the logo,
@AvaniVerma If you also feel good, kindly merge it.

**Review by Pratul1997 — APPROVED** [review]

**Comment by lalitmee** [comment]
Yeah, I also feel that the logo is good. :+1:

**Comment by AvaniVerma** [comment]
@adi44 The logo is pretty good but what about the SVG file ?

**Comment by adi44** [comment]
I will provide

**Comment by troublemagnet** [comment]
@adi44 when will you provide the SVG file?

**Comment by adi44** [comment]
today

**Comment by troublemagnet** [comment]
@adi44 please provide the logo by tomorrow morning else we'll have to close the PR!

**Pull request closed without merging**
